"""목표 섹션 - 다음 연도 추천 목표 및 액션 아이템."""

from __future__ import annotations

from typing import Any, List

from ...game_elements import GameRenderer


def generate_goals_section(
    repository_analyses: List[Any], year: int
) -> List[str]:
    """다음 연도 목표 생성 (HTML 버전)."""
    lines = [
        f"## 🎯 {year + 1}년 퀘스트 목표",
        "",
        f"> {year}년의 경험을 바탕으로 한 다음 시즌 추천 퀘스트",
        "",
    ]

    # Collect all improvement suggestions
    all_suggestions = []
    for repo in repository_analyses:
        for improvement in repo.improvements:
            suggestions = improvement.get("suggestions", [])
            all_suggestions.extend(suggestions)

    # Deduplicate and limit
    unique_suggestions = list(dict.fromkeys(all_suggestions))[:5]

    if unique_suggestions:
        lines.append("### 💡 추천 성장 방향")
        lines.append("")

        # Build suggestion cards
        suggestion_content = ""
        for idx, suggestion in enumerate(unique_suggestions, 1):
            suggestion_content += f"{idx}. 🎯 {suggestion}\n"

        # Render as info box
        lines.extend(GameRenderer.render_info_box(
            title="다음 레벨로 올라가기 위한 핵심 포커스",
            content=suggestion_content.strip(),
            emoji="💡",
            bg_color="#f0fdf4",
            border_color="#10b981"
        ))

    lines.append("### 🚀 실행 액션 아이템")
    lines.append("")

    # Build action items as HTML checklist
    action_items = [
        "📖 각 저장소의 상세 피드백 검토하기",
        "🎯 주요 개선 영역에 대한 구체적이고 측정 가능한 목표 설정",
        "🔧 새로운 기술 탐험 또는 현재 스택의 전문성 심화",
        "🤝 협업 및 코드 리뷰 참여 확대",
        f"📊 {year + 1}년 내내 분기별 진행 상황 추적"
    ]

    lines.append('<div style="border: 2px solid #e2e8f0; border-radius: 8px; padding: 20px; margin: 16px 0; background: white; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">')
    lines.append('  <h4 style="margin: 0 0 16px 0; color: #2d3748; font-size: 1.2em;">새로운 시즌을 준비하는 체크리스트</h4>')
    lines.append('  <div style="display: flex; flex-direction: column; gap: 12px;">')

    for item in action_items:
        lines.append('    <label style="display: flex; align-items: center; cursor: pointer; padding: 12px; background: #f7fafc; border-radius: 6px; transition: background 0.2s;">')
        lines.append('      <input type="checkbox" style="margin-right: 12px; width: 18px; height: 18px; cursor: pointer;">')
        lines.append(f'      <span style="color: #2d3748; font-size: 1em;">{item}</span>')
        lines.append('    </label>')

    lines.append('  </div>')
    lines.append('</div>')
    lines.append("")

    lines.append("---")
    lines.append("")
    return lines


def generate_footer() -> List[str]:
    """게임 스타일 푸터 생성 (HTML 버전)."""
    return [
        "## 🎉 모험의 마무리",
        "",
        '<div style="border: 3px solid #fbbf24; border-radius: 12px; padding: 30px; margin: 20px 0; background: linear-gradient(135deg, #fef3c7 0%, #fde68a 100%); text-align: center; box-shadow: 0 4px 6px rgba(251, 191, 36, 0.3);">',
        '  <div style="font-size: 2em; margin-bottom: 20px;">🌟</div>',
        '  <h2 style="margin: 0 0 20px 0; color: #78350f; font-size: 1.8em;">축하합니다, 용감한 개발자여!</h2>',
        '  <p style="margin: 0 0 20px 0; color: #92400e; font-size: 1.1em; line-height: 1.6;">',
        '    모든 커밋, PR, 리뷰가 당신의 성장에 기여했습니다.<br>',
        '    이 보고서로 성과를 축하하고 지속적인 성장을 계획하세요.',
        '  </p>',
        '  <div style="background: rgba(255,255,255,0.5); border-radius: 8px; padding: 16px; margin: 20px 0;">',
        '    <div style="font-size: 1.2em; color: #78350f; font-weight: bold; margin-bottom: 8px;">💡 기억하세요</div>',
        '    <div style="font-size: 1.1em; color: #92400e; font-style: italic;">"완벽한 한 번보다 꾸준한 진보가 더 강합니다!"</div>',
        '  </div>',
        '  <div style="font-size: 1.5em; margin-top: 20px; color: #78350f; font-weight: bold;">🚀 계속 전진하세요! 🚀</div>',
        '</div>',
        "",
        "---",
        "",
        '<div style="text-align: center; margin: 20px 0; padding: 20px; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); border-radius: 8px; color: white;">',
        '  <div style="font-size: 1.2em; margin-bottom: 8px;">⚔️ Generated by GitHub Feedback Analysis Tool ⚔️</div>',
        '  <div style="font-style: italic; opacity: 0.9;">당신의 코딩 여정을 응원합니다!</div>',
        '</div>',
        "",
    ]


__all__ = ["generate_goals_section", "generate_footer"]
